### ISSUE TITLE
How to call other methods of emacs env?

### ISSUE THREAD

**Issue by cireu** [ubolonton/emacs-module-rs#14]
There are other functions defined in `emacs-module.h` such as `vec_get` `vec_size`. How to call these method?

Or would you like to impl trait `FromLisp` for Vec?

**Comment by ubolonton** [comment]
Vector functions should be exposed through `Env`.

I would be happy to take a pull request for those. I haven't added them only because I haven't found the need yet.

**Comment by ubolonton** [comment]
Commit https://github.com/ubolonton/emacs-module-rs/commit/881b38d5326dd9a5fcf8bec0dead687690b8f32f enables these on a new type: `Vector` (`.get()`, `.set()`, `.size()`).
They are in release [0.10.0](https://github.com/ubolonton/emacs-module-rs/releases/tag/0.10.0).

**Comment by cireu** [comment]
Nice Job :+1:
