### ISSUE TITLE
Better way to call Lisp functions

### ISSUE THREAD

**Issue by ubolonton** [ubolonton/emacs-module-rs#15]
Currently Lisp functions are called using `Env::call`. This has 2 drawbacks:
- Arguments and return value must be of type `Value`. This requires a lot of `.into_lisp(env)?` and `.into_rust()` boilerplate.
- Heap allocation is needed to hold the raw `emacs_value` arguments, while most of the time the number of arguments is statically known.

These can be solved by a macro. A basic version already exists as an internal macro: [`call_lisp!`](https://github.com/ubolonton/emacs-module-rs/blob/52f427d/src/macros.rs#L45).

**Comment by sebastiencs** [comment]
How about an `Env::call` like that:
```rust
fn call(&self, name: &str, args: &[impl IntoLisp]) -> Result<Value<'_>>
```
Maybe with a trait similar to `IntoLisp` that doesn't take the ownership of the values ?

**Comment by ubolonton** [comment]
That would only work when all arguments have the same type.

```rust
// Would work.
env.call("list", &[1, 2])

// Wouldn't work.
env.call("list", &[1, "2"])
```

Besides, it wouldn't solve the heap allocation issue, since slices are dynamic sized.

**Comment by ubolonton** [comment]
Maybe we could use tuples instead of slices.

```rust
env.call("list", (1, "2"))
```

That would probably be a new trait with implementations for tuples, arrays and slices.

```rust
call(&self, name: &str, impl IntoLispArgs) -> Result<Value>
```
