### ISSUE TITLE
macOS live reloading documentation outdated

### ISSUE THREAD

**Issue by kommen** [ubolonton/emacs-module-rs#22]
In the readme it says:

> Note: This doesn't work on macOS 10.13+ (High Sierra and up). See Rust's issue #28794.

This seems outdated though, as the [linked issue is already resolved](https://github.com/rust-lang/rust/issues/28794#issuecomment-376785923).

**Comment by ubolonton** [comment]
It's not actually outdated. In older macOS versions, unloading used to work, with UB. Newer versions fixed that by disable unloading if there's a remote chance of UB.

I'll update the doc to clarify this point.
