### ISSUE TITLE
[emacs_module] 'unexpected close delimiter'

### ISSUE THREAD

**Issue by BorisKourt** [ubolonton/emacs-module-rs#23]
I am using [a plugin for nvim](https://github.com/eraserhd/parinfer-rust) that leverages this library. When I try to run `cargo build --release`, it fails on the `emacs_module` build step:

```sh
   Compiling emacs_module v0.10.0
error: unexpected close delimiter: `]`
   --> <...>/.local/share/nvim/plugged/parinfer-rust/target/release/build/emacs_module-9fb3f11fcc6e3c12/out/emacs_module.rs:112:40
    |
112 | # [ derive ( Copy , Clone ) ]; 16usize ] , }# [ test ]
    |                                        ^ unexpected close delimiter

error: aborting due to previous error

error: Could not compile `emacs_module`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Looking at the library `cargo.toml` file, it looks like the latest version is supplied:

```toml
emacs = "0.11.0"
```

I haven't seen any other issues about this, so I am wondering if there is some problem specific to my setup?

**Comment by ubolonton** [comment]
- What is your OS? What is the version?
- Do you have `clang` installed?
- Can you post the full `emacs_module.rs` file mentioned above somewhere?

**Comment by BorisKourt** [comment]
_OS:_ `macos 10.14.6`
_Clang:_ `Apple LLVM version 10.0.1 (clang-1001.0.46.4)`
_File:_ [At offending line](https://gist.github.com/BorisKourt/624569321952e13165ffbe3b7694ade3#file-emacs_module-rs-L112)

**Comment by ubolonton** [comment]
Can you check your `rustfmt` version? Are you using Rust nightly or stable?
The issue looks similar to [this](https://github.com/rust-lang/rust-bindgen/issues/1174).

**Comment by BorisKourt** [comment]
Apologies, this is on my end. I completely forgot that brew wasn't managing my rust install, this was caused by an outdated rustfmt version. 

Thanks for taking the time.
