### ISSUE TITLE
[Feature Request] Consider impl IntoLispArgs for AsRef<[T]> where T: IntoLisp

### ISSUE THREAD

**Issue by cireu** [ubolonton/emacs-module-rs#24]
Some time I found it's usual to convert a Vec of type implemented `IntoLisp` (e.g. `Vec<String>` ) trait to a Lisp list. 

But `env.list` just accept a type implemented `IntoLispArgs` , so  only `AsRef<[Value]>` or tuple of type implemented `IntoLisp`  can be used. 

I have to convert a `Vec<String>` to `Vec<Value>` and `map` can't be used here since `into_lisp` return a `Result<Value>`.

Can you consider impl IntoLispArgs for `AsRef<[T]>` where T: IntoLisp?

**Comment by ubolonton** [comment]
> Can you consider impl IntoLispArgs for `AsRef<[T]>` where T: IntoLisp?

I think such an implementation cannot be compiled (`rustc --explain E0207`).

> But `env.list` just accept a type implemented `IntoLispArgs` , so only `AsRef<[Value]>` or tuple of type implemented `IntoLisp` can be used.
> 
> I have to convert a `Vec<String>` to `Vec<Value>` and `map` can't be used here since `into_lisp` return a `Result<Value>`.

You can do it like below:

```rust
fn to_list(env: &Env, vec: Vec<String>) -> Result<Value> {
    env.list(
        &vec.into_iter()
            .map(|s| s.into_lisp(env))
            .collect::<Result<Vec<Value>>>()?
    )
}
```

**Comment by cireu** [comment]
Good! I learn a new Rust trick now~ Thanks a lot!

**Comment by gagbo** [comment]
Hello,


> You can do it like below:
> 
> ```rust
> fn to_list(env: &Env, vec: Vec<String>) -> Result<Value> {
>     env.list(
>         &vec.into_iter()
>             .map(|s| s.into_lisp(env))
>             .collect::<Result<Vec<Value>>>()?
>     )
> }
> ```

I’m having an issue with this code, because when it’s included in a function that has a defun macro, the compiler cannot compile as it apparently sees the `env` reference as leaking outside the scope of the generated code:

```console
$ RUSTFLAGS="-Zmacro-backtrace" cargo +nightly check
# ...
error[E0521]: borrowed data escapes outside of function
   --> src/emacs_wrapper.rs:244:1
    |
244 | #[defun(user_ptr, mod_in_name = false)]
    | -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | |
    | `env` is a reference that is only valid in the function body
    | `env` escapes the function body here
    | let's call the lifetime of this reference `'1`
    | argument requires that `'1` must outlive `'static`
    | in this procedural macro expansion
    |
   ::: /home/gagbo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/emacs-macros-0.17.0/src/lib.rs:111:1
    |
111 | pub fn defun(attr_ts: TokenStream, item_ts: TokenStream) -> TokenStream {
    | ----------------------------------------------------------------------- in this expansion of `#[defun]`

For more information about this error, try `rustc --explain E0521`.
warning: `parinfer_rust` (lib) generated 4 warnings
error: could not compile `parinfer_rust` (lib) due to 1 previous error; 4 warnings emitted
```

Do you have any idea how to deal with this issue? I’m basically trying to return a `Vec<String>` as a `Vector`.

Ref: justinbarclay/parinfer-rust#6

**Comment by ubolonton** [comment]
> Do you have any idea how to deal with this issue? I’m basically trying to return a `Vec<String>` as a `Vector`.
> 
> Ref: [justinbarclay/parinfer-rust#6](https://github.com/justinbarclay/parinfer-rust/pull/6)

```rust
#[defun(user_ptr, mod_in_name = false)]
fn get_option<'a>(options: &Options, option_name: Value<'a>) -> Result<Value<'a>>
```

You can just remove `user_ptr`, since this function doesn't return one. That flag means wrapping the the returned value in a `RefCell`, and giving it to Emacs as a `user-ptr`. The return type is `Value<'e>`, which contains a reference to `env`.

**Comment by gagbo** [comment]
Thanks a lot, I’ll try to read more about the defun macro next time sorry!
