### ISSUE TITLE
IntoIter trait for Vector type?

### ISSUE THREAD

**Issue by cireu** [ubolonton/emacs-module-rs#27]
IMO it's a good way to iterate a lisp vector in Rust. Would this cause any UB?

**Comment by ubolonton** [comment]
It would not cause any UB. I just haven't come up with an acceptable interface yet. `Vector::get` returns a `Result`, so a naive `Iterator` implementation would have `type Item = Result<Value<'e>>`, but `type Item = Value<'e>` is more desirable.

I'm thinking about changing `Vector` from a newtype wrapper into this instead:

```rust
struct Vector<'e> {
    value: Value<'e>, // Type-checked upon creation
    size: usize, // Retrieved upon creation
}
```
