### ISSUE TITLE
[discussion] writing json parser as rust module

### ISSUE THREAD

**Issue by yyoncho** [ubolonton/emacs-module-rs#4]
Thanks for your work on this package!

I am working on lsp-mode which at this stage of the project has issues with the performance of json parsing and I am investigating what are the options to implement it as a Rust emacs module and the potential optimization effect. I am rust beginner and in general, I do not have a lot of low-level programming knowledge and I have few questions regarding whether the whole approach will make sense. 
Generally, do you think this approach is feasible? I know that the json parsing will be very fast in rust, but what about the code that will convert from rust data structures to emacs one? Do you think that running it in a separate thread and then reporting it to the emacs-lsp thread will work in case we want to parse several responses in parallel (e. g. using a thread pool to create async parse json function)?

**Comment by sebastiencs** [comment]
Hi @yyoncho 

> I am working on lsp-mode which at this stage of the project has issues with the performance of json parsing

The C function `json-parse-string` still have performance issue ? I found it faster than the elisp implementation in `json.el`

I wrote a simple implementation of a function that convert a json string to an elisp object [there](https://github.com/sebastiencs/emacs-json/blob/master/src/lib.rs).
This is very basic and one might implement the `Deserializer` Trait from the `serde` library to improve performances.

The major bottleneck of emacs native modules is that emacs will convert all inputs string to utf8, even if the module provide already utf8 strings.
This operation isn't particulary slow, but it is noticeable with big/lots of strings.
The function `json-parse-string` [have a similar behavior](https://github.com/emacs-mirror/emacs/blob/cbcb5718761dc645c291110ceb7250628510b1dc/src/json.c#L228), it might explain the performance issues you're seeing. Also you can take a look at [this thread](https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-04/msg00419.html).

> Generally, do you think this approach is feasible? I know that the json parsing will be very fast in rust, but what about the code that will convert from rust data structures to emacs one? Do you think that running it in a separate thread and then reporting it to the emacs-lsp thread will work in case we want to parse several responses in parallel (e. g. using a thread pool to create async parse json function)?

Apart from that, yes and it will be for sure way faster than the current implementation

**Comment by yyoncho** [comment]
@sebastiencs thanks for jumping in and for the rust code, this is exactly what I am looking for.

> The C function `json-parse-string` still have performance issue ? I found it faster than the elisp implementation in `json.el`

I am testing with it with emacs -q + patched latest version of lsp-mode to make it work with native json and it does not feel smooth and some of the requests are very slow(e. g. the completion). I will try to do some testing with your library too.

**Comment by yyoncho** [comment]
@sebastiencs 

Here it is some data with ~3.5mb json response from dart server:

```
(let ((lsp-response-timeout 10000))
     (with-current-buffer "main.dart"
       (lsp-request
        "textDocument/completion"
        (lsp--text-document-position-params))))
```
```
lsp-request                                            1           2.827734776   2.827734776
lsp--parser-on-message                                 1           2.239950487   2.239950487
lsp--read-json                                         1           2.232859334   2.232859334
lsp--parser-read                                       520         0.1208285060  0.0002323625
lsp--log-request-time                                  1           0.0070152     0.0070152
lsp-log                                                1           0.006991619   0.006991619
lsp-request-async                                      1           0.005800155   0.005800155
lsp--send-request-async                                1           0.00579042    0.00579042
lsp--make-message                                      1           0.005114124   0.005114124
lsp-ui-doc--hide-frame                                 5           0.0028144520  0.0005628904
lsp--create-async-callback                             2           0.000581002   0.000290501
lsp--text-document-position-params                     1           0.000136625   0.000136625
lsp-ui-doc--get-frame                                  10          0.0001244280  1.244...e-05
lsp--buffer-uri                                        1           0.000106544   0.000106544
lsp--lens-idle-function                                108         0.0001054459  9.763...e-07
lsp--path-to-uri                                       1           8.8438e-05    8.8438e-05
lsp-ui-doc--make-buffer-name                           5           5.574...e-05  1.114...e-05
lsp--send-no-wait                                      1           2.9148e-05    2.9148e-05
lsp--find-workspaces-for                               1           1.0542e-05    1.0542e-05
lsp--parse-header                                      1           7.998e-06     7.998e-06
lsp-workspace-root                                     5           7.756e-06     1.5512e-06
lsp--merge-results                                     1           5.661e-06     5.661e-06
lsp--cur-workspace-check                               1           5.524e-06     5.524e-06
lsp--parser-reset                                      1           3.04e-06      3.04e-06
lsp-workspaces                                         2           2.866e-06     1.433e-06
lsp--get-body-length                                   1           2.341e-06     2.341e-06
lsp--get-message-type                                  1           1.489e-06     1.489e-06
```

**Comment by yyoncho** [comment]
Actually, it turns out the whole issue is caused by way string is passed to the parse function:

```
-        (json-parse-string str :object-type 'hash-table
-                           :null-object nil :false-object nil)
+        (with-temp-buffer
+          (insert str)
+          (json-parse-string (buffer-string) :object-type 'hash-table
+                             :null-object nil :false-object nil))

```

This change speeded up the code 15 times.

**Comment by sebastiencs** [comment]
@yyoncho Yep I had the same observation in the thread [I mentionned](https://lists.gnu.org/archive/html/bug-gnu-emacs/2018-04/msg00419.html).
But even after looking at the C code, I didn't find out why the current buffer affect the performance of this function..
Just a nit, I think this might be enough, without copying the whole string in the buffer:
```diff
-        (json-parse-string str :object-type 'hash-table
-                           :null-object nil :false-object nil)
+        (with-temp-buffer
+          (json-parse-string str :object-type 'hash-table
+                             :null-object nil :false-object nil))
```

**Comment by yyoncho** [comment]
@sebastiencs thanks, will try it out. I identified a few more bottlenecks in `lsp-mode` and after fixing them it lsp-mode feels like it is flying... I will work on preparing a PR.
