### ISSUE TITLE
0.16.1 didn't pick up ARM fix

### ISSUE THREAD

**Issue by nwjsmith** [ubolonton/emacs-module-rs#40]
👋 I saw that there was a new release (thanks!) but I don't think it picked up the `bindgen` upgrade because [the version of `emacs_module` wasn't bumped from `0.12.0`](https://github.com/ubolonton/emacs-module-rs/blob/a8b837b95914408e92f8901a1573d00136dbf999/emacs-module/Cargo.toml). I think a bump to `0.12.1` in `emacs_module`, and then for `emacs` to `0.16.2` should get the fix released.

**Comment by ubolonton** [comment]
Thanks for spotting this! I just published another version to fix this.
