### ISSUE TITLE
How to call Elisp functions from a backgroud thread?

### ISSUE THREAD

**Issue by zbelial** [ubolonton/emacs-module-rs#53]
I wannt to start a new thread and then call Elisp functions within that thread, but I found that Env does not implement Sync or Send. So is there anyway to archive my goal? Thanks. 

More information about my use case:  
I'd like to start a subprocess and read repeatedly its output in a loop in a thread, after reading in some data, I'll call a Elisp function to tell Emacs.

**Comment by zbelial** [comment]
It seems that `emacs-env` itself does not support this use case. Closing this issue.

**Comment by ubolonton** [comment]
This is now possible in 0.21, via `env.open_channel`, instead of timers.
- Doc: https://ubolonton.github.io/emacs-module-rs/latest/open-channel.html
- It's used in `ewm`: https://codeberg.org/ezemtsov/ewm/src/branch/master/compositor/src/module.rs#L5
